BarberShop/BarberShop/Controllers/ClientsController.cs
using BarberShop.Entities;
using BarberShop.Exeptions;
using BarberShop.Exeptions.Throws;
using BarberShop.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace BarberShop.Controllers
{
    [Route("api/[controller]")]
    [Authorize(Roles = "admin")]
    public class ClientsController : Controller
    {
        private readonly ICrudService<Client> _crudService;

        public ClientsController(ICrudService<Client> crudService)
        {
            _crudService = crudService;
        }

        /// <summary>
        /// Обновление клиента
        /// </summary>
        /// <param name="clientId">id клиента</param>
        /// <returns></returns>
        [HttpGet("Update")]
        public IActionResult Update(Guid clientId)
        {
            var client = new Client();
            try
            {
                client = _crudService.Get(clientId);

            }
            catch (ServiceOperationException exception)
            {
                ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
            }
            return View(client);
        }

        /// <summary>
        /// Возвращает всех клиентов
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GetAll(string name, string phone)
        {
            var clients = new List<Client>();
            try
            {
                clients =_crudService.GetAll();
                if (!String.IsNullOrEmpty(name))
                {
                    clients = clients.FindAll(x => x.Name.Contains(name));
                }
                if (!String.IsNullOrEmpty(phone))
                {
                    clients = clients.FindAll(x => x.Phone.Contains(phone));
                }

            }
            catch (ServiceOperationException exception)
            {
                ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
            }
            return View(clients);
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Создание клиента
        /// </summary>
        /// <param name="client">клиент</param>
        /// <returns></returns>
        [HttpPost("Create")]
        public IActionResult Create( Client client)
        {
            if (ModelState.IsValid)
            {
                var createdMaster = new List<Client>();
                var error = new List<Error>();

                try
                {
                    createdMaster.Add(_crudService.Create(client));
                }
                catch (ServiceOperationException exception)
                {
                    ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
                    return View(client);
                }

                return RedirectToAction("GetAll");
            }
            return View(client);
        }
        /// <summary>
        /// Обновить клиента
        /// </summary>
        /// <param name="client">клиент</param>
        /// <returns></returns>
        [HttpPost("Update")]
        public IActionResult Update( Client client)
        {
            if (ModelState.IsValid)
            {
                var updatedClient = new List<Client>();

                try
                {
                    updatedClient.Add(_crudService.Update(client));
                }
                catch (ServiceOperationException exception)
                {
                    ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
                    return View(client);
                }
                return RedirectToAction("GetAll");
            }
            return View(client);
        }

        /// <summary>
        /// Удалить клиента
        /// </summary>
        /// <param name="clientId">id клиента</param>
        /// <returns></returns>
        [HttpDelete("{ClientId:guid}")]
        public IActionResult Delete(Guid clientId)
        {
            var deletedClient = new List<Client>();

            try
            {
                deletedClient.Add(_crudService.Delete(clientId));
            }
            catch (Exception)
            {
                throw new Exception("Не удалось удалить клиента");
            }

            return Json(new { Data = deletedClient });
        }

    }
}

BarberShop/BarberShop/Controllers/MastersController.cs
using BarberShop.DataStorages;
using BarberShop.Entities;
using BarberShop.Exeptions;
using BarberShop.Exeptions.Throws;
using BarberShop.Models;
using BarberShop.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace BarberShop.Controllers
{
    [Route("api/[controller]")]
    public class MastersController : Controller
    {
        private readonly ICrudService<Master> _crudService;
        private Guid userId = new Guid("60a69d44-f6fd-4915-b039-d064b9e3934f");
        private readonly BarberShopContext _context;
        public MastersController(ICrudService<Master> crudService, BarberShopContext context)
        {
            _crudService = crudService;
            _context = context;
        }


        /// <summary>
        /// Возвращает мастера по id
        /// </summary>
        /// <param name="masterId">id мастера</param>
        /// <returns></returns>
        //[HttpGet("{masterId:guid}")]
        public IActionResult Get(Guid masterId)
        {
            var master = new Master();
            try
            {
                master=_crudService.Get(masterId);

            }
            catch (ServiceOperationException exception)
            {
                ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
            }
            return View(master);
        }

        /// <summary>
        /// Возвращает всех мастеров
        /// </summary>
        /// <returns></returns>
        [HttpGet("GetAll")]
        public IActionResult GetAll()
        {
            var masters = new List<Master>();
            try
            {
                masters.AddRange(_crudService.GetAll());

            }
            catch (ServiceOperationException exception)
            {
                ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
            }
            return View(masters.ToArray());
        }
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Создать мастера
        /// </summary>
        /// <param name="master"></param>
        /// <returns></returns>
        [HttpPost("Create")]
        public IActionResult Create( MasterViewModel master)
        {
            if (ModelState.IsValid)
            {
                var createdMaster = new List<Master>();
                var error = new List<Error>();

                try
                {
                    createdMaster.Add(_crudService.Create(master));
                    User user = new User { Phone = master.Phone, Password = master.Password, FullName = master.FullName, RoleId= userId };
                    _context.Users.Add(user);
                    _context.SaveChanges();
                }
                catch (ServiceOperationException exception)
                {
                    ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
                    return View(master);
                }

                return RedirectToAction("Get", "MasterServices", new { masterId = master.Id  });
            }
            return View(master);
        }
        /// <summary>
        /// Обновить мастера
        /// </summary>
        /// <param name="master"></param>
        /// <returns></returns>
        [HttpPost("Update")]
        public IActionResult Update( Master master)
        {
            if (ModelState.IsValid)
            {
                var updatedMaster = new List<Master>();

                try
                {
                    updatedMaster.Add(_crudService.Update(master));
                }
                catch (ServiceOperationException exception)
                {
                    ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
                    return View(master);
                }
                return RedirectToAction("GetAll");
            }
            return View(master);
        }

        /// <summary>
        /// Удалить мастера
        /// </summary>
        /// <param name="masterId"></param>
        /// <returns></returns>
        //[HttpDelete("{masterId:guid}")]
        [HttpGet("Delete")]
        public IActionResult Delete(Guid masterId)
        {
            var deletedMaster = new List<Master>();

            try
            {
                deletedMaster.Add(_crudService.Delete(masterId));
            }
            catch (ServiceOperationException exception)
            {
                ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
            }

            return RedirectToAction("GetAll");
        }
        
    }
}

BarberShop/BarberShop/Controllers/VisitsController.cs
using BarberShop.Entities;
using BarberShop.Exeptions;
using BarberShop.Exeptions.Throws;
using BarberShop.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using BarberShop.Services.interfaces;
using System.Security.Claims;


namespace BarberShop.Controllers
{
    [Route("api/[controller]")]
    public class VisitsController : Controller
    {
        private readonly ICrudService<Visit> _crudService;
        private readonly ICrudService<Client> _clientCrudService;
        private readonly IMasterServiceCrudService<MasterServices> _masterServiceCrudService;
        private readonly ICrudService<Master> _masterCrudService;
        private readonly IServiceInVisitCrudService<ServiceInVisit> _serviceInVisitCrudService;
        private readonly ICrudService<Service> _serviceCrudService;

        public VisitsController(ICrudService<Visit> crudService,
            ICrudService<Client> clientCrudService, 
            IMasterServiceCrudService<MasterServices> masterServiceCrudService,
            ICrudService<Master> masterCrudService,
            IServiceInVisitCrudService<ServiceInVisit> serviceInVisitCrudService,
            ICrudService<Service> serviceCrudService)
        {
            _crudService = crudService;
            _clientCrudService = clientCrudService;
            _masterServiceCrudService = masterServiceCrudService;
            _masterCrudService = masterCrudService;
            _serviceInVisitCrudService = serviceInVisitCrudService;
            _serviceCrudService = serviceCrudService;
        }
        /// <summary>
        /// Возвращает посещение по id
        /// </summary>
        /// <param name="visitId">id поcещения</param>
        /// <returns></returns>
        [HttpGet("Update")]
        public IActionResult Update(Guid visitId)
        {
            var visit = new Visit();
            try
            {
                ViewBag.sm = new SelectList(_clientCrudService.GetAll(), "Id", "Name");
                visit = _crudService.Get(visitId);
                ViewBag.ClientName = _clientCrudService.GetAll().Select(x=>x.Name).ToList();
                ViewBag.Masters = _masterServiceCrudService.GetAll().Select(x => x.Master.FullName).Distinct().ToList();
                ViewBag.Service = _masterServiceCrudService.GetAll().Where(x => x.Master.FullName == ViewBag.Masters[0]).Select(x => x.Service.NameOfService).ToList();
            }
            catch (ServiceOperationException exception)
            {
                ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
            }
            return View(visit);
        }
        /// <summary>
        /// Возвращает все поcещения
        /// </summary>
        /// <returns></returns>
        [HttpGet("GetAll")]
        public IActionResult GetAll(string userName)
        {
            var visits = new List<Visit>();
            try
            {
                if (userName!="empty")
                {
                    visits = _crudService.GetAll();
                    if (!String.IsNullOrEmpty(userName))
                    {
                        visits = visits.FindAll(x=>x.Client.Name.Contains(userName)).ToList();
                    }
                }
            }
            catch (ServiceOperationException exception)
            {
                ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
            }
            return View(visits);
        }

        [HttpGet("Create")]
        public IActionResult Create(string name)
        {
            var visit = new Visit();
            visit.Client = _clientCrudService.GetAll().FirstOrDefault(x => x.Name == name);
            if (visit.Client == null)
            {
                return RedirectToAction("Login", "Account");
            }
            visit.ClientId = visit.Client.Id;
            //ViewBag.Client = new SelectList(_clientCrudService.GetAll(), "Id", "Name");
            return View(visit);
        }

        /// <summary>
        /// Создать поcещение
        /// </summary>
        /// <param name="visit"></param>
        /// <returns></returns>
        [HttpPost("Create")]
        public IActionResult Create( Visit visit)
        {
            //DateOfVisitDateValidation dateOfVisitDateValidation = new DateOfVisitDateValidation();
            if (ModelState.IsValid)
            {
                var createdVisit = new List<Visit>();

                try
                {
                    createdVisit.Add(_crudService.Create(visit));
                }
                catch (ServiceOperationException exception)
                {
                    ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
                    return View(createdVisit);
                }
                return RedirectToAction("Get","ServicesInVisits",new { visitId = visit.Id});
            }
            visit.Client = _clientCrudService.Get(visit.ClientId);
            return View(visit);
        }

        /// <summary>
        /// Обновить посещение
        /// </summary>
        /// <param name="visit"></param>
        /// <returns></returns>
        [HttpPost("Update")]
        public IActionResult Update(Visit visit)
        {
            if (ModelState.IsValid)
            {
                var updatedVisit = new List<Visit>();

                try
                {                    
                    _crudService.Update(visit);
                }
                catch (ServiceOperationException exception)
                {
                    ViewBag.Error = ErrorFactory.IdentifyExceptionByType(exception).Description;
                    ViewBag.ClientName = _clientCrudService.GetAll().Select(x => x.Name).ToList();
                    return View(visit);
                }
                return RedirectToAction("GetAll", new { userName = _clientCrudService.Get(visit.ClientId).Name });
            }
            return View(visit);
        }

        /// <summary>
        /// Удалить посещение
        /// </summary>
        /// <param name="visitId"></param>
        /// <returns></returns>
        [HttpGet("Delete")]
        public IActionResult Delete(Guid visitId)
        {
            var userName = _crudService.Get(visitId).Client.Name;
            try
            {
                _crudService.Delete(visitId);
            }
            catch (Exception)
            {
                ViewBag.Error = "Не удалось удалить посещение";
                return RedirectToAction("GetAll");
            }

            return RedirectToAction("GetAll", new { userName = userName });
        }

        [HttpGet("NotAuthorizedUser")]
        public IActionResult NotAuthorizedUser()
        {
            return View();
        }
    }
}

BarberShop/BarberShop/Views/Shared/_AutorizedUser.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<button style="background-color: #222;" class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Привет @User.Claims.Last().Value!
    
    <span class="caret"></span>
</button>
<ul class="dropdown-menu" aria-labelledby="dropdownMenu1" style="        margin-right: 5%;
        background-color: #222;
        color: #9d9d9d;">
    <li><a style="background-color: #222;
    color: #9d9d9d;
    text-align: center;" asp-area="" asp-controller="Account" asp-action="Edit" asp-route-Id="@User.Claims.First().Value">Изменить</a></li>
</ul>

<li>
    <form style="padding-top: 8px;" asp-area="" asp-controller="Account" asp-action="Logout">
        <button type="submit" class="nav-link btn btn-link text-dark">Выйти</button>
    </form>
</li>

<style>
    .dropdown-toggle{
    padding-top: 14px;border-top-width: 1px;border: none;padding-bottom: 14px; color:#9d9d9d;
    }
    .dropdown-toggle:hover { color:#fff;}
    .open > .dropdown-toggle.btn-default:focus{
        color: #fff;
    }
</style>

BarberShop/BarberShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html style="height: 100%;">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oldboy</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="height: 100%; padding-bottom:0px; margin-bottom: 0px;">
    <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Oldboy</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (User.Claims.Count() == 0)
                        {
                            <li><a asp-area="" asp-controller="Visits" asp-action="GetAll" asp-route-userName="empty">Посещения</a></li>
                        }
                        else if (User.Claims.Count() != 0 && User.Claims.ElementAt(1).Value == "admin")
                        {
                            <li><a asp-area="" asp-controller="Visits" asp-action="GetAll">Посещения</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Visits" asp-action="GetAll" asp-route-userName="@User.Claims.Last().Value">Посещения</a></li>
                        }
                        <li><a asp-area="" asp-controller="Masters" asp-action="GetAll">Парикмахеры</a></li>
                        @if (User.Claims.Count() != 0 && User.Claims.ElementAt(1).Value == "admin")
                        {
                            <li><a asp-area="" asp-controller="Clients" asp-action="GetAll">Клиенты</a></li>
                        }
                        <li><a asp-area="" asp-controller="Services" asp-action="GetAll">Услуги</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">О нас</a></li>
                    </ul>
                    <partial name="_LoginPartial" />


                </div>
            </div>
        </nav>

    <partial name="_CookieConsentPartial" />
    <div style=" position: relative;min-height: 100%; padding-top:51px;">
        <div class="container body-content" style="padding-bottom: 40px;">
            @RenderBody()

        </div>
        <footer style="background-color:black;position: absolute;left: 0;bottom: 0;width: 100%;height: 40px;">
            <div style="color:white">
                <h4 style="text-align:center">Адрес: ул. Вершинина, 22 &nbsp;&nbsp;&nbsp; Телефон: +7-923-689-74-56 &nbsp;&nbsp;&nbsp;  Режим работы: ПН-ВС 10:00-21:00</h4>
            </div>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>